hip_hop = [
    ['Kendrick Lamar', 'To Pimp a Butterfly', 'hip_hop'], 
    ['Madvillain', 'Madvillainy', 'hip_hop'], 
    ['Kendrick Lamar', 'good kid, m.A.A.d city', 'hip_hop'], 
    ['Nas', 'Illmatic', 'hip_hop'], 
    ['Wu-Tang Clan', 'Enter the Wu-Tang (36 Chambers)', 'hip_hop'], 
    ['Kanye West', 'My Beautiful Dark Twisted Fantasy', 'hip_hop'], 
    ['Death Grips', 'The Money Store', 'hip_hop'], 
    ['Danny Brown', 'Atrocity Exhibition', 'hip_hop'], 
    ['A Tribe Called Quest', 'The Low End Theory', 'hip_hop'], 
    ['Kanye West', 'The College Dropout', 'hip_hop'], 
    ['DJ Shadow', 'Endtroducing.....', 'hip_hop'], 
    ['MF DOOM', 'MM..FOOD', 'hip_hop'], 
    ['J Dilla', 'Donuts', 'hip_hop'], 
    ['OutKast', 'Aquemini', 'hip_hop'], 
    ['GZA', 'Liquid Swords', 'hip_hop'], 
    ['A Tribe Called Quest', 'Midnight Marauders', 'hip_hop'], 
    ['Kanye West', 'Late Registration', 'hip_hop'], 
    ['Mobb Deep', 'The Infamous', 'hip_hop'], 
    ['Freddie Gibbs & Madlib', 'Piñata', 'hip_hop'], 
    ['OutKast', 'ATLiens', 'hip_hop'], 
    ['The Notorious B.I.G.', 'Ready to Die', 'hip_hop'], 
    ['A Tribe Called Quest', 'We got it from Here… Thank You 4 Your service', 'hip_hop'], 
    ['Tyler, the Creator', 'Flower Boy', 'hip_hop'], 
    ['Mos Def', 'Black on Both Sides', 'hip_hop'], 
    ['JPEGMAFIA', 'LP!', 'hip_hop'], 
    ['KIDS SEE GHOSTS', 'KIDS SEE GHOSTS', 'hip_hop'], 
    ['Little Simz', 'Sometimes I Might Be Introvert', 'hip_hop'], 
    ['Viktor Vaughn', 'Vaudeville Villain', 'hip_hop'], 
    ['JPEGMAFIA', 'Scaring the Hoes', 'hip_hop'], 
    ['Gang Starr', 'Moment of Truth', 'hip_hop'], 
    ['Lauryn Hill', 'The Miseducation of Lauryn Hill', 'hip_hop'], 
    ['Kanye West', 'Yeezus', 'hip_hop'], 
    ['Earl Sweatshirt', 'Some Rap Songs', 'hip_hop'], 
    ['Death Grips', 'Bottomless Pit', 'hip_hop'], 
    ['The Roots', 'Things Fall Apart', 'hip_hop'], 
    ['Beastie Boys', 'Paul\'s Boutique', 'hip_hop'], 
    ['Nujabes', 'Modal Soul', 'hip_hop'], 
    ['Organized Konfusion', 'Stress: The Extinction Agenda', 'hip_hop'], 
    ['Public Enemy', 'It Takes a Nation of Millions to Hold Us Back', 'hip_hop'], 
    ['Raekwon', 'Only Built 4 Cuban Linx...', 'hip_hop'], 
    ['Racionais MC\'s', 'Sobrevivendo no inferno', 'hip_hop'], 
    ['Lil Ugly Mane', 'Mista Thug Isolation', 'hip_hop'], 
    ['Three-6 Mafia', 'Mystic Stylez', 'hip_hop'], 
    ['Danger Mouse', 'Cheat Codes', 'hip_hop'], 
    ['Mach-Hommy', 'The G.A.T...', 'hip_hop'], 
    ['JID', 'The Forever Story', 'hip_hop'], 
    ['OutKast', 'Stankonia', 'hip_hop'], 
    ['Deltron 3030', 'Deltron 3030', 'hip_hop'], 
    ['Black Star', 'Mos Def & Talib Kweli Are Black Star', 'hip_hop'], 
    ['Kanye West', 'The Life of Pablo', 'hip_hop'], 
    ['Jay-Z', 'Reasonable Doubt', 'hip_hop'], 
    ['Big L', 'Lifestylez ov da Poor & Dangerous', 'hip_hop'], 
    ['MF DOOM', 'Operation: Doomsday', 'hip_hop'], 
    ['Clipse', 'Hell Hath No Fury', 'hip_hop'], 
    ['Racionais MC\'s', 'Nada como um dia após o outro dia', 'hip_hop'], 
    ['Common', 'Be', 'hip_hop'], 
    ['billy woods', 'Aethiopes', 'hip_hop'], 
    ['Ghostface Killah', 'Supreme Clientele', 'hip_hop'], 
    ['Ghostface Killah', 'Ironman', 'hip_hop'], 
    ['The Pharcyde', 'Bizarre Ride II the Pharcyde', 'hip_hop'], 
    ['UGK', 'Ridin\' Dirty', 'hip_hop'], 
    ['Gravediggaz', '6 Feet Deep', 'hip_hop'], 
    ['Danny Brown', 'XXX', 'hip_hop'], 
    ['Pusha T', 'DAYTONA', 'hip_hop'], 
    ['Digable Planets', 'Blowout Comb', 'hip_hop'], 
    ['Jay-Z', 'The Blueprint', 'hip_hop'], 
    ['Travis Scott', 'Rodeo', 'hip_hop'], 
    ['Cannibal Ox', 'The Cold Vein', 'hip_hop'], 
    ['De La Soul', 'Buhloone Mind State', 'hip_hop'], 
    ['Snoop Doggy Dogg', 'Doggystyle', 'hip_hop'], 
    ['The Roots', 'Game Theory', 'hip_hop'], 
    ['Farazi v Kayra', 'Hayalet Islığı', 'hip_hop'], 
    ['Run the Jewels', 'Run the Jewels 2', 'hip_hop'], 
    ['Pete Rock & C.L. Smooth', 'The Main Ingredient', 'hip_hop'], 
    ['De La Soul', 'Stakes Is High', 'hip_hop'], 
    ['Dr. Dre', 'The Chronic', 'hip_hop'], 
    ['Tiro de Gracia', 'Ser hümano!!', 'hip_hop'], 
    ['Public Enemy', 'Fear of a Black Planet', 'hip_hop'], 
    ['Denzel Curry', 'TA13OO', 'hip_hop'], 
    ['clipping.', 'Visions of Bodies Being Burned', 'hip_hop'], 
    ['Freddie Gibbs & Madlib', 'Bandana', 'hip_hop'], 
    ['King Geedorah', 'Take Me to Your Leader', 'hip_hop'], 
    ['The Roots', 'Illadelph Halflife', 'hip_hop'], 
    ['Goodie Mob', 'Soul Food', 'hip_hop'], 
    ['De La Soul', '3 Feet High and Rising', 'hip_hop'], 
    ['Little Brother', 'The Minstrel Show', 'hip_hop'], 
    ['Sagopa Kajmer', 'Bir Pesimistin Gözyaşları', 'hip_hop'], 
    ['Lil Ugly Mane', 'Third Side of Tape', 'hip_hop'], 
    ['A Tribe Called Quest', 'People\'s Instinctive Travels and the Paths of Rhythm', 'hip_hop'], 
    ['Pete Rock & C.L. Smooth', 'Mecca and the Soul Brother', 'hip_hop'], 
    ['BROCKHAMPTON', 'Saturation II', 'hip_hop'], 
    ['Little Simz', 'GREY Area', 'hip_hop'], 
    ['Tyler, the Creator', 'Call Me If You Get Lost', 'hip_hop'], 
    ['Jay-Z', 'The Black Album', 'hip_hop'], 
    ['billy woods', 'Hiding Places', 'hip_hop'], 
    ['Big K.R.I.T.', '4eva Is a Mighty Long Time', 'hip_hop'], 
    ['Scarface', 'The Diary', 'hip_hop'], 
    ['BROCKHAMPTON', 'Saturation III', 'hip_hop'], 
    ['Nujabes', 'Metaphorical Music', 'hip_hop'], 
    ['The Pharcyde', 'Labcabincalifornia', 'hip_hop'], 
    ['Denzel Curry', 'Melt My Eyez See Your Future', 'hip_hop'], 
    ['Beastie Boys', 'Ill Communication', 'hip_hop'], 
    ['Blu & Exile', 'Below the Heavens', 'hip_hop'], 
    ['CunninLynguists', 'A Piece of Strange', 'hip_hop'], 
    ['The Rockwood Escape Plan', 'Dreamcast Summer Songs', 'hip_hop'], 
    ['Koopsta Knicca', 'Da Devil\'s Playground: Underground Solo', 'hip_hop'], 
    ['Quasimoto', 'The Unseen', 'hip_hop'], 
    ['Digable Planets', 'Reachin\' (A New Refutation of Time and Space)', 'hip_hop'], 
    ['Kool G Rap & DJ Polo', 'Live and Let Die', 'hip_hop'], 
    ['Ice Cube', 'Death Certificate', 'hip_hop'], 
    ['Mobb Deep', 'Hell on Earth', 'hip_hop'], 
    ['Gang Starr', 'Hard to Earn', 'hip_hop'], 
    ['Kool G Rap', '4, 5, 6', 'hip_hop'], 
    ['The V.O.S. Family', 'Come - N - 2 - My World', 'hip_hop'], 
    ['Dälek', 'Absence', 'hip_hop'], 
    ['Pete Rock', 'Center of Attention', 'hip_hop'], 
    ['Dälek', 'From Filthy Tongue of Gods and Griots', 'hip_hop'], 
    ['Mach-Hommy', 'HBO (Haitian Body Odor)', 'hip_hop'], 
    ['Fugees', 'The Score', 'hip_hop'], 
    ['Ghostface Killah', 'Fishscale', 'hip_hop']
]